version: "3.7"
services:

  transifex-delivery:
    image: transifex-delivery-devel
    env_file: docker-compose.env
    stdin_open: true
    tty: true
    depends_on:
      - transifex-delivery-redis

  transifex-delivery-redis:
    image: redis:latest
    command: redis-server
