app:
  name: transifex-delivery
  port: 10300

settings:
  request_size_limit: '50mb'
  upload_timeout_min: 10
  cache_ttl: 5400
  disk_storage_path: '/tmp'
  token_whitelist: ''
  syncer: transifex
  cache: redis

transifex:
  api_host: https://rest.api.transifex.com

redis:
  host: redis://transifex-delivery-redis
  cache_expire_min: 21600
  registry_prefix: reg-
  cache_prefix: cache-

metrics:
  enabled: true
  port: 9090

log:
  transports:
    console:
      level: info

workers: 1
