app:
  name: transifex-delivery
  port: 10300

settings:
  request_size_limit: '50mb'
  upload_timeout_min: 10
  cache_ttl: 1800
  autosync_min: 60
  disk_storage_path: '/tmp'
  token_whitelist: ''
  syncer: transifex
  cache: redis

transifex:
  api_host: https://rest.api.transifex.com

redis:
  host: redis://transifex-delivery-redis

registry:
  prefix: 'registry:'
  expire_min: 10080

cache:
  redis:
    prefix: 'storage:'
    expire_min: 10080
  s3:
    bucket: 'transifex-delivery'
    acl: 'private'
    location: 'cache://'
    max_age: 86400

metrics:
  enabled: false
  port: 9090

log:
  transports:
    console:
      level: info

queue:
  name: sync
  workers: 1

analytics:
  enabled: true
  retention_days: 180