app:
  name: transifex-delivery
  port: 10300

settings:
  trust_proxy: true
  request_size_limit: '50mb'
  upload_timeout_min: 10
  auth_cache_min: 30
  push_throttle_timeout_min: 10
  pull_success_cache_min: 10080
  pull_error_cache_min: 15
  cache_ttl: 1800
  autosync_min: 60
  disk_storage_path: '/tmp'
  token_whitelist: ''
  trust_secret: ''
  syncer: transifex
  cache: redis
  keep_alive_timeout_sec: ''

transifex:
  api_host: https://rest.api.transifex.com
  page_limit: 1000

redis:
  host: redis://transifex-delivery-redis

registry:
  prefix: 'registry:'

cache:
  redis:
    prefix: 'storage:'
    expire_min: 10080
  s3:
    bucket: 'transifex-delivery'
    acl: 'private'
    location: 'cache://'
    max_age: 86400

metrics:
  enabled: false
  port: 9090

log:
  transports:
    console:
      level: info

queue:
  name: sync
  workers: 1

analytics:
  enabled: true
  retention_days: 180
