log:
  silent: true

registry:
  prefix: 'test:registry:'

cache:
  redis:
    prefix: 'test:storage:'
  s3:
    create_bucket: true

queue:
  name: 'test:sync'
  workers: 0

settings:
  trust_secret: 'txsecret'

dynamodb:
  tableName: transifex-delivery-test

telemetry:
  enabled: false

aws:
  config:
    common:
      region: eu-west-1
      credentials:
        accessKeyId: keyid
        secretAccessKey: accesskey
    s3:
      endpoint: http://transifex-delivery-moto:5000
      s3ForcePathStyle: true
    dynamodb:
      endpoint: http://transifex-delivery-dynamodb:8000
